# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\borya\PycharmProjects\lab4\my_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1086, 595)
        self.buttonCreateGraf = QtWidgets.QPushButton(Dialog)
        self.buttonCreateGraf.setGeometry(QtCore.QRect(410, 320, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateGraf.setFont(font)
        self.buttonCreateGraf.setObjectName("buttonCreateGraf")
        self.TextLineName = QtWidgets.QTextEdit(Dialog)
        self.TextLineName.setGeometry(QtCore.QRect(200, 170, 371, 31))
        self.TextLineName.setObjectName("TextLineName")
        self.buttonAddInfo = QtWidgets.QPushButton(Dialog)
        self.buttonAddInfo.setGeometry(QtCore.QRect(40, 210, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonAddInfo.setFont(font)
        self.buttonAddInfo.setObjectName("buttonAddInfo")
        self.TextLineCountSales = QtWidgets.QTextEdit(Dialog)
        self.TextLineCountSales.setGeometry(QtCore.QRect(240, 260, 71, 30))
        self.TextLineCountSales.setObjectName("TextLineCountSales")
        self.CountSales = QtWidgets.QLabel(Dialog)
        self.CountSales.setGeometry(QtCore.QRect(40, 260, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CountSales.setFont(font)
        self.CountSales.setObjectName("CountSales")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, 160, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(200, 20, 81, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TextLineA1 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.TextLineA1.setObjectName("TextLineA1")
        self.verticalLayout_3.addWidget(self.TextLineA1)
        self.TextLineA2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.TextLineA2.setObjectName("TextLineA2")
        self.verticalLayout_3.addWidget(self.TextLineA2)
        self.TextLineA = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.TextLineA.setObjectName("TextLineA")
        self.verticalLayout_3.addWidget(self.TextLineA)
        self.TextLineB = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.TextLineB.setObjectName("TextLineB")
        self.verticalLayout_3.addWidget(self.TextLineB)
        self.buttonAddX = QtWidgets.QPushButton(Dialog)
        self.buttonAddX.setGeometry(QtCore.QRect(320, 260, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonAddX.setFont(font)
        self.buttonAddX.setObjectName("buttonAddX")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(600, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.listNames = QtWidgets.QListWidget(Dialog)
        self.listNames.setGeometry(QtCore.QRect(600, 40, 171, 121))
        self.listNames.setObjectName("listNames")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(800, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.listForX = QtWidgets.QListWidget(Dialog)
        self.listForX.setGeometry(QtCore.QRect(800, 40, 171, 121))
        self.listForX.setObjectName("listForX")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Нечеткая логика и лингвистические шкалы"))
        self.buttonCreateGraf.setText(_translate("Dialog", "Выполнить"))
        self.TextLineName.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.buttonAddInfo.setText(_translate("Dialog", "Добавить данные"))
        self.TextLineCountSales.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CountSales.setText(_translate("Dialog", "Введите объем продаж"))
        self.label.setText(_translate("Dialog", " Координата а1"))
        self.label_3.setText(_translate("Dialog", " Координата а"))
        self.label_2.setText(_translate("Dialog", " Координата а2"))
        self.label_4.setText(_translate("Dialog", " Координата b"))
        self.label_5.setText(_translate("Dialog", "Название шкалы"))
        self.TextLineA1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextLineA2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextLineA.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextLineB.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.buttonAddX.setText(_translate("Dialog", "Добавить х"))
        self.label_6.setText(_translate("Dialog", "Список шкал"))
        self.label_7.setText(_translate("Dialog", "Список X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
